INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador A', 'I7 16GB SSD1T', 5403);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador B', 'I7 16GB SSD2T', 6403);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador C', 'I7 16GB SSD2T', 1234);

-- Nessa area, objetos podem ser criados apartir de codigos sql 